### ISSUE TITLE
asciicast of string-edit.el no longer works in asciinema

### ISSUE THREAD

**Issue by diamond-lizard** [magnars/string-edit.el#12]
The asciicast of string-edit.el no longer works in asciinema:

```
> asciinema play https://asciinema.org/a/3040
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/asciinema/asciicast.py", line 105, in load
    raise LoadError('unsupported asciicast format')
asciinema.asciicast.LoadError: unsupported asciicast format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/asciinema", line 11, in <module>
    load_entry_point('asciinema==1.4.0', 'console_scripts', 'asciinema')()
  File "/usr/lib64/python3.4/site-packages/asciinema/__main__.py", line 109, in main
    code = command.execute()
  File "/usr/lib64/python3.4/site-packages/asciinema/commands/play.py", line 17, in execute
    self.player.play(asciicast.load(self.filename), self.max_wait, self.speed)
  File "/usr/lib64/python3.4/site-packages/asciinema/asciicast.py", line 117, in load
    except json.decoder.JSONDecodeError as e:
AttributeError: 'module' object has no attribute 'JSONDecodeError'
```

I think this is probably because the format of the old asciicast is incompatible with the current version of asciinema (1.4.0).

It might be a good idea to update the asciicast to a newer version, or maybe just make an animated gif out of it, or maybe even a video screencast posted on a video hosting site like youtube or vimeo.

**Comment by magnars** [comment]
Thanks for letting me know. Since it still works on the web, I'm not going to put any more work into it at this point.
